@@include("../../blocks/modules/header/header.js")
@@include("../../blocks/modules/header/header.js")
@@include("../../blocks/modules/modals/modals.js")
@@include("../../blocks/modules/main-burger/main-burger.js")
@@include("../../blocks/modules/solutions/solutions.js")
@@include("../../blocks/modules/s-stocks/s-stocks.js")
@@include("../../blocks/modules/s-news/s-news.js")
@@include("../../blocks/modules/accordion/accordion.js")
@@include("../../blocks/modules/s-map/s-map.js")
@@include("../../blocks/modules/preloader/preloader.js")
@@include("../../blocks/modules/tabs-block/tabs-block.js")
@@include("../../blocks/modules/home-intro/home-intro.js")
@@include("../../blocks/modules/home-catalog/home-catalog.js")
@@include("../../blocks/modules/s-about/s-about.js")
@@include("../../blocks/modules/s-download/s-download.js")
@@include("../../blocks/modules/s-faq/s-faq.js")
@@include("../../blocks/modules/s-docs/s-docs.js")
@@include("../../blocks/modules/s-catalog/s-catalog.js")
@@include("../../blocks/modules/s-title/s-title.js")
@@include("../../blocks/modules/prods-list/prods-list.js")
@@include("../../blocks/modules/solution-intro/solution-intro.js")
@@include("../../blocks/modules/gallery-slider/gallery-slider.js")
@@include("../../blocks/modules/cards-slider/cards-slider.js")
@@include("../../blocks/modules/pc-slider/pc-slider.js")
@@include("../../blocks/modules/samples-list/samples-list.js")

document.addEventListener('DOMContentLoaded', () => {
    header();
    preloader();
    modalsInit();
    mainBurger();
    solutionsSlider();
    stocksSlider();
    newsSlider();
    accordion();
    sMap();
    tabsBlockInit();
    homeCatalogAnim();
    sAboutAnim();
    sDownloadAnim();
    sFaqAnim();
    sDocsAnim();
    sCatalogAnim();
    sTitleAnim();
    prodsListAnim();
    gallerySlider();
    cardsSlider();
    pcSlider();
    samplesListAnim();
})